# Generated by Django 4.2.7 on 2023-12-29 04:44

from django.db import migrations, models
import sistema.validator


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Emprestimo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=50)),
                ("user_cpf", models.CharField(default="", max_length=14)),
                ("emprestimo_data", models.DateField(default=None, null=True)),
                (
                    "devolucao_data",
                    models.DateField(blank=True, default=None, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Funcionario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_completo",
                    models.CharField(
                        default="",
                        max_length=50,
                        validators=[sistema.validator.validate_name],
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        default="",
                        max_length=50,
                        validators=[sistema.validator.validate_telefone],
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        default="",
                        max_length=250,
                        validators=[sistema.validator.validate_email],
                    ),
                ),
                (
                    "nascimento",
                    models.DateField(
                        default=None,
                        null=True,
                        validators=[sistema.validator.validate_nascimento],
                    ),
                ),
                (
                    "cpf",
                    models.CharField(
                        default="",
                        max_length=14,
                        unique=True,
                        validators=[sistema.validator.validate_cpf],
                    ),
                ),
                ("senha", models.CharField(default="", max_length=50)),
                ("cidade", models.CharField(max_length=50)),
                ("habilitado", models.BooleanField(default=False)),
                ("estado", models.CharField(max_length=50)),
            ],
            options={
                "permissions": [
                    ("emprestar", "pode fazer emprestimo"),
                    ("cadastrar_livro", "pode cadastrar livro"),
                    ("excluir_livro", "pode excluir livro"),
                    ("criar_usuario", "pode criar usuario"),
                    ("excluir_usuario", "pode excluir usuario"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Livro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("livro_id", models.PositiveIntegerField(default=None, unique=True)),
                ("nome", models.CharField(max_length=50)),
                ("autor", models.CharField(max_length=50)),
                ("editora", models.CharField(max_length=50)),
                ("ano", models.PositiveIntegerField(default=None)),
                ("emprestado", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_completo",
                    models.CharField(
                        default="",
                        max_length=50,
                        validators=[sistema.validator.validate_name],
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        default="",
                        max_length=50,
                        validators=[sistema.validator.validate_telefone],
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        default="",
                        max_length=250,
                        validators=[sistema.validator.validate_email],
                    ),
                ),
                (
                    "nascimento",
                    models.DateField(
                        default=None,
                        null=True,
                        validators=[sistema.validator.validate_nascimento],
                    ),
                ),
                (
                    "cpf",
                    models.CharField(
                        default="",
                        max_length=14,
                        unique=True,
                        validators=[sistema.validator.validate_cpf],
                    ),
                ),
                ("senha", models.CharField(default="", max_length=50)),
                ("instituicao", models.CharField(max_length=50)),
                ("idade", models.PositiveIntegerField(default=None)),
                ("estado", models.CharField(default="", max_length=2)),
                ("cidade", models.CharField(default="", max_length=50)),
                ("rua", models.CharField(default="", max_length=50)),
                ("numero", models.PositiveIntegerField(default=None)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
