# Generated by Django 4.2.7 on 2024-01-04 21:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Emprestimo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=50)),
                ("user_cpf", models.CharField(default="", max_length=14)),
                ("emprestimo_data", models.DateField(default=None, null=True)),
                (
                    "devolucao_data",
                    models.DateField(blank=True, default=None, null=True),
                ),
            ],
            options={
                "verbose_name": "Empréstimo",
                "verbose_name_plural": "Empréstimos",
            },
        ),
        migrations.CreateModel(
            name="Funcionario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("habilitado", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Funcionário",
                "verbose_name_plural": "Funcionários",
            },
        ),
        migrations.CreateModel(
            name="Livro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("livro_id", models.PositiveIntegerField(default=None, unique=True)),
                ("nome", models.CharField(max_length=100)),
                ("autor", models.CharField(max_length=50)),
                ("editora", models.CharField(max_length=50)),
                ("ano", models.PositiveIntegerField(default=None)),
                ("emprestado", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Livro",
                "verbose_name_plural": "Livros",
            },
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("instituicao", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "usuário",
                "verbose_name_plural": "usuários",
            },
        ),
    ]
