# Generated by Django 4.2.7 on 2023-12-01 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Gerente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("senha", models.CharField(max_length=50)),
                ("cpf", models.CharField(default="", max_length=14)),
            ],
            options={
                "permissions": [
                    ("excluir_funcionario", "pode excluir funcionario"),
                    ("aprovar_funcionario", "pode aprovar funcionario"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Livro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("livro_id", models.IntegerField(default=0)),
                ("nome", models.CharField(max_length=50)),
                ("autor", models.CharField(max_length=50)),
                ("editora", models.CharField(max_length=50)),
                ("ano", models.IntegerField(default=0)),
                ("emprestado", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_completo", models.CharField(default="", max_length=50)),
                ("telefone", models.CharField(default="", max_length=50)),
                ("email", models.EmailField(default="", max_length=250)),
                ("senha", models.CharField(default="", max_length=50)),
                ("nascimento", models.DateField(default=None, null=True)),
                ("cpf", models.CharField(default="", max_length=14)),
                ("instituicao", models.CharField(max_length=50)),
                ("idade", models.IntegerField()),
                ("estado", models.CharField(default="", max_length=2)),
                ("cidade", models.CharField(default="", max_length=50)),
                ("rua", models.CharField(default="", max_length=50)),
                ("numero", models.IntegerField(default=0)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Funcionario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_completo", models.CharField(default="", max_length=50)),
                ("telefone", models.CharField(default="", max_length=50)),
                ("email", models.EmailField(default="", max_length=250)),
                ("senha", models.CharField(default="", max_length=50)),
                ("nascimento", models.DateField(default=None, null=True)),
                ("cpf", models.CharField(default="", max_length=14)),
                ("cidade", models.CharField(max_length=50)),
                ("habilitado", models.BooleanField(default=False)),
                ("estado", models.CharField(max_length=50)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("emprestar", "pode fazer emprestimo"),
                    ("cadastrar_livro", "pode cadastrar livro"),
                    ("excluir_livro", "pode excluir livro"),
                    ("criar_usuario", "pode criar usuario"),
                    ("excluir_usuario", "pode excluir usuario"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Emprestimo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=50)),
                ("user_cpf", models.CharField(default="", max_length=14)),
                ("emprestimo_data", models.DateField(default=None, null=True)),
                (
                    "devolucao_data",
                    models.DateField(blank=True, default=None, null=True),
                ),
                (
                    "livro_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sistema.livro"
                    ),
                ),
            ],
        ),
    ]
