# Generated by Django 4.2.7 on 2023-12-27 02:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sistema", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="funcionario",
            name="cpf",
            field=models.CharField(default="", max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name="gerente",
            name="cpf",
            field=models.CharField(default="", max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name="livro",
            name="ano",
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name="livro",
            name="livro_id",
            field=models.IntegerField(default=None, unique=True),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="cpf",
            field=models.CharField(default="", max_length=14, unique=True),
        ),
    ]
