# Generated by Django 4.2.7 on 2023-11-19 19:46

import cpf_field.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sistema", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Endereco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("estado", models.CharField(default="", max_length=2)),
                ("cidade", models.CharField(default="", max_length=50)),
                ("rua", models.CharField(default="", max_length=50)),
                ("numero", models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name="emprestimo",
            name="livro_info",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="emprestimo",
            name="status",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="funconario",
            name="cpf",
            field=cpf_field.models.CPFField(
                default="", max_length=14, verbose_name="cpf"
            ),
        ),
        migrations.AddField(
            model_name="funconario",
            name="email",
            field=models.EmailField(default="", max_length=250),
        ),
        migrations.AddField(
            model_name="funconario",
            name="first_name",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="funconario",
            name="last_name",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="funconario",
            name="nascimento",
            field=models.DateField(default=type(None)),
        ),
        migrations.AddField(
            model_name="funconario",
            name="senha",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="funconario",
            name="telefone",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="usuario",
            name="cpf",
            field=cpf_field.models.CPFField(
                default="", max_length=14, verbose_name="cpf"
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="email",
            field=models.EmailField(default="", max_length=250),
        ),
        migrations.AddField(
            model_name="usuario",
            name="first_name",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="usuario",
            name="last_name",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="usuario",
            name="nascimento",
            field=models.DateField(default=type(None)),
        ),
        migrations.AddField(
            model_name="usuario",
            name="senha",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="usuario",
            name="telefone",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="emprestimo",
            name="devolucao_data",
            field=models.DateTimeField(default=type(None)),
        ),
        migrations.AlterField(
            model_name="emprestimo",
            name="emprestimo_data",
            field=models.DateTimeField(default=type(None)),
        ),
        migrations.AddField(
            model_name="usuario",
            name="endereco",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="sistema.endereco",
            ),
        ),
    ]
