# Generated by Django 4.2.7 on 2024-01-04 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sistema", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="funcionario",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="emprestimo",
            name="livro_info",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="sistema.livro"
            ),
        ),
    ]
