# Generated by Django 4.2.7 on 2023-12-28 20:59

from django.db import migrations, models
import sistema.validator


class Migration(migrations.Migration):
    dependencies = [
        ("sistema", "0002_alter_funcionario_cpf_alter_gerente_cpf_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="funcionario",
            name="cpf",
            field=models.CharField(
                default="",
                max_length=14,
                unique=True,
                validators=[sistema.validator.validate_cpf],
            ),
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="email",
            field=models.EmailField(
                default="",
                max_length=250,
                validators=[sistema.validator.validate_email],
            ),
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="nascimento",
            field=models.DateField(
                default=None,
                null=True,
                validators=[sistema.validator.validate_nascimento],
            ),
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="nome_completo",
            field=models.CharField(
                default="", max_length=50, validators=[sistema.validator.validate_name]
            ),
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="telefone",
            field=models.CharField(
                default="",
                max_length=50,
                validators=[sistema.validator.validate_telefone],
            ),
        ),
        migrations.AlterField(
            model_name="livro",
            name="ano",
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name="livro",
            name="livro_id",
            field=models.PositiveIntegerField(default=None, unique=True),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="cpf",
            field=models.CharField(
                default="",
                max_length=14,
                unique=True,
                validators=[sistema.validator.validate_cpf],
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="email",
            field=models.EmailField(
                default="",
                max_length=250,
                validators=[sistema.validator.validate_email],
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="idade",
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="nascimento",
            field=models.DateField(
                default=None,
                null=True,
                validators=[sistema.validator.validate_nascimento],
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="nome_completo",
            field=models.CharField(
                default="", max_length=50, validators=[sistema.validator.validate_name]
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="numero",
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="telefone",
            field=models.CharField(
                default="",
                max_length=50,
                validators=[sistema.validator.validate_telefone],
            ),
        ),
    ]
