# Generated by Django 4.2.7 on 2024-01-01 04:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sistema", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emprestimo",
            options={
                "verbose_name": "Empréstimo",
                "verbose_name_plural": "Empréstimos",
            },
        ),
        migrations.AlterModelOptions(
            name="funcionario",
            options={
                "verbose_name": "Funcionário",
                "verbose_name_plural": "Funcionário",
            },
        ),
        migrations.AlterModelOptions(
            name="livro",
            options={"verbose_name": "Livro", "verbose_name_plural": "Livros"},
        ),
        migrations.AlterModelOptions(
            name="usuario",
            options={"verbose_name": "usuário", "verbose_name_plural": "usuário"},
        ),
    ]
