# Generated by Django 4.2.7 on 2023-11-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sistema", "0002_endereco_emprestimo_livro_info_emprestimo_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="funconario",
            name="habilitado",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="livro",
            name="emprestado",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="emprestimo",
            name="devolucao_data",
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name="emprestimo",
            name="emprestimo_data",
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name="funconario",
            name="nascimento",
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="nascimento",
            field=models.DateField(default=None),
        ),
    ]
