# Generated by Django 4.2.7 on 2023-11-21 20:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sistema", "0003_funconario_habilitado_livro_emprestado_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="funconario",
            old_name="first_name",
            new_name="nome_completo",
        ),
        migrations.RenameField(
            model_name="usuario",
            old_name="first_name",
            new_name="nome_completo",
        ),
        migrations.RemoveField(
            model_name="funconario",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="last_name",
        ),
    ]
