# Generated by Django 4.2.7 on 2023-11-23 00:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sistema", "0005_rename__id_livro_livro_id"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Funconario",
            new_name="Funcionario",
        ),
    ]
