# Generated by Django 4.2.7 on 2023-11-23 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sistema", "0006_rename_funconario_funcionario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emprestimo",
            name="livro_info",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="sistema.livro"
            ),
        ),
    ]
