# Generated by Django 4.2.7 on 2023-11-25 05:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sistema", "0008_remove_usuario_endereco_funcionario_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emprestimo",
            name="devolucao_data",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="emprestimo",
            name="emprestimo_data",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="nascimento",
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="nascimento",
            field=models.DateField(default=None, null=True),
        ),
    ]
